parameters:
#    merlin_store.example.class: Merlin\StoreBundle\Example

services:
#    merlin_store.example:
#        class: %merlin_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    merlin.tv_shows.form.type.tvshow:
        class: Merlin\StoreBundle\Form\TvShowType
        tags:
            - { name: form.type, alias: merlin_storebundle_tvshow }
