assetic:
    assets:
# Per screen
        add_show_js:
            inputs:
                - @MerlinTvShowsBundle/Resources/public/js/add_show.js
        list_shows_js:
            inputs:
                - @MerlinTvShowsBundle/Resources/public/js/list_shows.js
                - @MerlinTvShowsBundle/Resources/public/js/confirmationDialog.js
        edit_show_js:
            inputs:
                - @MerlinTvShowsBundle/Resources/public/js/edit_show.js
# App wide
        jquery_js:
            inputs:
                - %kernel.root_dir%/../vendor/frameworks/jquery/jquery.js
                - %kernel.root_dir%/../vendor/bmatzner/jquery-ui-bundle/Bmatzner/JQueryUIBundle/Resources/public/js/jquery-ui.js
        jquery_css:
            input:
                - %kernel.root_dir%/../vendor/bmatzner/jquery-ui-bundle/Bmatzner/JQueryUIBundle/Resources/public/css/base/jquery-ui.css
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css
        bootstrap_fonts:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/fonts/glyphicons-halflings-regular.eot
                - %kernel.root_dir%/../vendor/twitter/bootstrap/fonts/glyphicons-halflings-regular.svg
                - %kernel.root_dir%/../vendor/twitter/bootstrap/fonts/glyphicons-halflings-regular.ttf
                - %kernel.root_dir%/../vendor/twitter/bootstrap/fonts/glyphicons-halflings-regular.woff
