merlin_tv_shows_homepage:
    pattern:  /
    defaults: { _controller: MerlinTvShowsBundle:Default:index }

shows_add:
    pattern: /shows/add
    defaults: { _controller: MerlinTvShowsBundle:Shows:add }

shows_edit:
    pattern: /shows/edit/{id}
    defaults: { _controller: MerlinTvShowsBundle:Shows:edit }

fonts:
    pattern: /fonts/{name}
    defaults: { _controller: MerlinTvShowsBundle:Asset:fonts }
