merlin_tv_shows_homepage:
    pattern:  /
    defaults: { _controller: MerlinTvShowsBundle:Shows:index }

shows_add:
    pattern: /shows/add
    defaults: { _controller: MerlinTvShowsBundle:Shows:add }

shows_edit:
    pattern: /shows/edit/{id}
    defaults: { _controller: MerlinTvShowsBundle:Shows:edit }
    requirements:
        id: \d+

shows_delete:
    pattern: /shows/delete/{id}
    defaults: { _controller: MerlinTvShowsBundle:Shows:delete}
    requirements:
        id: \d+

shows_search:
    pattern: /shows/search/{id}/{provider}
    defaults: { _controller: MerlinTvShowsBundle:Shows:search}
    requirements:
        id: \d+
        provider: \w*

shows_episode:
    pattern: /shows/episode/{id}/{mode}
    defaults: { _controller: MerlinTvShowsBundle:Shows:episode}
    requirements:
        id: \d+
        mode: next|previous

fonts:
    pattern: /fonts/{name}
    defaults: { _controller: MerlinTvShowsBundle:Asset:fonts }

cssimages:
    pattern: /css/images/{name}
    defaults: { _controller: MerlinTvShowsBundle:Asset:cssimages }
